import type { Metadata } from "next";

import Heading from "@/components/heading";

export const metadata: Metadata = {
  title: "Projects | Melvin Otieno",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <Heading animate="Projects" />
    </>
  );
}
